import { IServiceProvider } from './types';

export default {
  name: 'Anthropic',
  apiBase: 'https://api.openrouter.ai/v1',
  currency: 'USD',
  options: {
    apiBaseCustomizable: true,
    apiKeyCustomizable: true,
  },
  chat: {
    apiSchema: ['base', 'key', 'model'],
    topP: { min: 0, max: 1, default: null },
    temperature: { min: 0, max: 1, default: 1.0 },
    options: {
      modelCustomizable: true,
    },
    models: {
      'anthropic/claude-3.7-sonnet:beta': {
        label: 'claude-3.7-sonnet-latest',
        contextWindow: 200000,
        maxTokens: 128000,
        defaultMaxTokens: 128000,
        inputPrice: 0.003,
        outputPrice: 0.015,
        toolEnabled: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowedMimeTypes: [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
          ],
        },
        description: `Highest level of intelligence and capability with toggleable extended thinking`,
        group: 'Claude-3.5',
      },
      'google/gemini-2.5-pro-exp-03-25:free': {
        label: 'gemini-2.5-pro',
        contextWindow: 1000000,
        maxTokens: 65535,
        defaultMaxTokens: 65535,
        inputPrice: 0.001,
        outputPrice: 0.001,
        toolEnabled: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowedMimeTypes: [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
          ],
        },
        description: `High level of intelligence and capability`,
        group: 'Claude-3.5',
      },
      'x-ai/grok-beta': {
        label: 'grok-3',
        contextWindow: 131072,
        maxTokens: 131072,
        defaultMaxTokens: 131072,
        inputPrice: 0.001,
        outputPrice: 0.001,
        description: `The fastest model of Anthropic, Intelligence at blazing speeds`,
        toolEnabled: true,
        group: 'Claude-3.5',
      },
      'openai/gpt-4o-mini': {
        label: '4o-mini',
        contextWindow: 128000,
        maxTokens: 4096,
        defaultMaxTokens: 4000,
        inputPrice: 0.0001,
        outputPrice: 0.0006,
        toolEnabled: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowedMimeTypes: [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
          ],
        },
        description: `Powerful multilingual model for highly complex tasks, top-level performance, intelligence, fluency, and understanding`,
        group: 'Claude-3',
      },
      'google/gemini-2.0-flash-001': {
        label: 'gemini-2-flash',
        contextWindow: 1000000,
        maxTokens: 8192,
        defaultMaxTokens: 8192,
        inputPrice: 0.0001,
        outputPrice: 0.0001,
        toolEnabled: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowedMimeTypes: [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
          ],
        },
        description:
          'A multilingual model with balance of intelligence and speed, strong utility, balanced for scaled deployments',
        group: 'Claude-3',
      },
      'google/gemini-2.0-pro-exp-02-05:free': {
        label: 'gemini-2-pro-free',
        contextWindow: 2000000,
        maxTokens: 8192,
        defaultMaxTokens: 8192,
        inputPrice: 0.00001,
        outputPrice: 0.00001,
        toolEnabled: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowedMimeTypes: [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
          ],
        },
        description:
          'Fastest and most compact multilingual model for near-instant responsiveness, quick and accurate targeted performance',
        group: 'Claude-3',
      },
    },
  },
} as IServiceProvider;
